### ISSUE TITLE
5.4 버전에서 더블 클릭 옵션이 동작하지 않음

### ISSUE THREAD

**Issue by caoko** [neverworkalone/naverdic#1]
dist에 결과물을 esbuild로 minify하지 않았을 경우, 잘 동작합니다.
minified의 script가 뭔가 오동작하고 있는 듯 합니다.

**Comment by genonfire** [comment]
5.4에서 더블 클릭 속도를 빠르게 설정해 그만큼 빠른 더블 클릭이 이뤄지지 않을 경우 동작하지 않게 된 듯 합니다. 
5.5에 더블 클릭 속도를 롤백했으며 더블 클릭 속도를 더 빠르게 / 더 느리게 설정할 수 있도록 설정을 추가 했습니다.
